name: Getting Started

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: hello world
      run: echo hello world
    - name: go version
      run: go --version